apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubelens.fullname" . }}
  labels:
    {{- include "kubelens.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubelens.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubelens.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "kubelens.fullname" . }}
      {{- else if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: kubelens
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: KUBELENS_CONFIG
              value: /etc/kubelens/config.yaml
            {{- if .Values.kubeconfig.existingSecret }}
            - name: KUBECONFIG
              value: /etc/kubeconfig
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/kubelens/config.yaml
              subPath: config.yaml
            {{- if .Values.kubeconfig.existingSecret }}
            - name: kubeconfig
              mountPath: /etc/kubeconfig
              subPath: {{ .Values.kubeconfig.key }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ default (printf "%s-config" (include "kubelens.fullname" .)) .Values.config.existingSecret }}
        {{- if .Values.kubeconfig.existingSecret }}
        - name: kubeconfig
          secret:
            secretName: {{ .Values.kubeconfig.existingSecret }}
        {{- end }}
